### ISSUE TITLE
Use config system to store GTM Container ID

### ISSUE THREAD

**Issue by sekjal** [Cyber-Duck/Silverstripe-Google-Tag-Manager#1]
Instead of directly placing the GTM Container ID in the Page_Controller, reference a setting in a YAML config.  This would allow multiple sites to share a common codebase for Page_Controller, while still keeping the Container ID out of the database (which would be problematic for dev/test/production scenarios where the database gets synced between different servers).

**Comment by Andrew-Mc-Cormack** [comment]
Hey. Yeah I have an update on my local machine that I ned to finish that moves the GTM ID to the YML config and works with the subsites module (allowing different containers for different sites). Will probably have it done some time this / next week. Will drop you a line when its pushed. Will be in the 1.1.0 release.

**Comment by sekjal** [comment]
Great!  Thanks @Andrew-Mc-Cormack!  Happy to help test

**Comment by Andrew-Mc-Cormack** [comment]
Updated on 4.0 branch for SilverStripe 4
